name: Update Classes

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [update_class]

jobs:
  classUpdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - id: update-src
        uses: metro420yt/class-update@v1
        with:
          folder: src
          ext: css
          diff: "https://raw.githubusercontent.com/SyndiShanX/Update-Classes/main/Changes.txt"
          
      - name: Revert folderIcon breakages
        run: |
          sed -i 's/\.folderHeader__48112/\.folderIcon__48112/g' src/**/*.css src/*.css 2>/dev/null || true

      - uses: EndBug/add-and-commit@v10
        id: commit-step
        if: ${{steps.update-src.outputs.totalChanges > 0}}
        with:
          default_author: github_actions
          message: "[bot] update classes"
          fetch: true
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Refresh Git State
        if: ${{ steps.commit-step.outputs.committed == 'true' }}
        run: |
          git fetch --prune --unshallow || git fetch --prune
          git pull --ff-only

      - name: Get changed files
        id: changed-files
        if: ${{ steps.commit-step.outputs.committed == 'true' }}
        uses: tj-actions/changed-files@v44
        with:
          base_sha: "HEAD~1"
          separator: "\n"

      - name: Process Git Metadata
        id: metadata
        if: ${{ steps.commit-step.outputs.committed == 'true' }}
        run: |
          # Use rev-parse to get the true current SHA
          TRUE_SHA=$(git rev-parse HEAD)
          echo "ACTUAL_SHA=$TRUE_SHA" >> $GITHUB_ENV
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.16.0
        if: ${{ steps.commit-step.outputs.committed == 'true' }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "File(s) changed"
          description: |
            **Repository:**
            [${{github.repository}}](https://github.com/${{github.repository}})

            **Event:**
            [`${{env.SHORT_SHA}}`](https://github.com/${{github.repository}}/commit/${{env.ACTUAL_SHA}}) - ${{env.COMMIT_TITLE}}
            
            **File(s) changed:**
            ```
            ${{steps.changed-files.outputs.all_changed_files}}
            ```
            **Triggered by:**
            Class Updater [bot]
          color: 0xac02be
          username: GitHub - dqcss
          avatar_url: ${{ secrets.AVATAR_URL }}
