name: Discord Status Notification

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          separator: "\n"

      - name: Process Git Metadata
        id: metadata
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
          IFS= read -r FIRST_LINE << 'EOF'
          ${{ github.event.head_commit.message }}
          EOF
          echo "COMMIT_TITLE=$FIRST_LINE" >> $GITHUB_ENV

      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.16.0
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          nodetail: true
          title: "File(s) changed"
          description: |
            **Repository:**
            [${{github.repository}}](https://github.com/${{github.repository}})
            
            **Event:**
            [`${{env.SHORT_SHA}}`](https://github.com/${{github.repository}}/commit/${{github.sha}}) - ${{env.COMMIT_TITLE}}
            
            **File(s) changed:**
            ```
            ${{steps.changed-files.outputs.all_changed_files}}
            ```
            **Triggered by:**
            ${{github.event.head_commit.author.name}}
          color: 0xac02be
          username: GitHub - dqcss
          avatar_url: ${{ secrets.AVATAR_URL }}
